### ISSUE TITLE
Wrong doctrine registry class

### ISSUE THREAD

**Issue by WarGeneration** [artprima/query-filter-bundle#10]
Argument 1 passed to Artprima\QueryFilterBundle\ParamConverter\ConfigConverter::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry or null, instance of Doctrine\Bundle\DoctrineBundle\Registry given

doctrine/orm: v2.7.3
symfony: v5.1

**Comment by denisvmedia** [comment]
There was a BC break in Doctrine. And it should be already fixed in Doctrine. Can you confirm it? @WarGeneration 
For the reference: https://github.com/doctrine/DoctrineBundle/pull/1202

**Comment by denisvmedia** [comment]
In addition, I made changes to the bundle itself, so the problem should be gone.

**Comment by WarGeneration** [comment]
Yes, now all is alright, ty
