### ISSUE TITLE
Package locked to 5.* version of sensio/framework-extra-bundle

### ISSUE THREAD

**Issue by bajke992** [artprima/query-filter-bundle#13]
If there are no major issues concerning version ^6.0 of sensio/framework-extra-bundle with this bundle, can the package composer.json be updated from ^5.1.5 to >=5.1.5? :)

**Comment by denisvmedia** [comment]
Well, I can try adding it as "^5.1.5|^6.0".

**Comment by denisvmedia** [comment]
Solved in 1.6.0.
