### ISSUE TITLE
Multiple search on one field

### ISSUE THREAD

**Issue by byhaskell** [artprima/query-filter-bundle#19]
Hello. Nice and functional bundle, thanks for your hard work.

You need to search for two or more values in one field.

There are no problems with searching by one value:
```/?filter[f.title]=test```

The options that I tried, but for one reason or another do not work:
```/?simple=0&filter[0][f.title][type]=like&filter[0][f.title]=test1&filter[1][f.title][type]=like&filter[1][f.title]=test2```
```/?filter[f.title][type]=like&filter[f.title][]=test1&filter[f.title][]=test2```
```/?filter[f.title][type]=like&filter[f.title][0]=test1&filter[f.title][1]=test2```
```/?filter[f.title][0][type]=like&filter[f.title][1][type]=like&filter[f.title][0]=test1&filter[f.title][1]=test2```

How to correctly compose a query with a search for one field with many values?

**Comment by denisvmedia** [comment]
Will this work for you?

```
simple=0&filter[0][field]=t.title&filter[0][type]=like&filter[0][x]=test1&filter[1][field]=t.title&filter[1][type]=like&filter[1][x]=test2&filter[1][connector]=or
```

**Comment by byhaskell** [comment]
@denisvmedia Thanks It works. Have a good day!)
