### ISSUE TITLE
Support for custom and prepared filters

### ISSUE THREAD

**Issue by byhaskell** [artprima/query-filter-bundle#20]
Hello. Thank you for this wonderful bundle, it removed thousands, maybe hundreds of thousands of lines from my code.

I connect your bundle to an existing one, so sometimes there are times when it is not possible to compose a request. Therefore, I would like to ask whether there will be support for named filters, for example, or any custom ones? What could be added to the example of kalbak for their performance and have an even stronger instrument?

For example, I came across the fact that the query contains the MYSQL functions DATE and DATE_SUB, which you cannot write in the filter.

Thanks in advance for your reply.

**Comment by denisvmedia** [comment]
Hi, thank you for your feedback :)

I think, `Artprima\QueryFilterBundle\QueryFilter\Config\Alias` is something you need. As I can see, I didn't document it, but you can see an example in this test:
https://github.com/artprima/query-filter-bundle/blob/master/tests/unit/QueryFilter/QueryFilterTest.php#L509

Basically, by using Alias - apart from having complex queries - you can also avoid exposing column names.

**Comment by byhaskell** [comment]
@denisvmedia Thank aliyasy regarded as a hidden field names, but did not think for complex queries, I will try)
