### ISSUE TITLE
Hangs on request

### ISSUE THREAD

**Issue by byhaskell** [artprima/query-filter-bundle#21]
Hello.
I make a simple filter - everything works well, but problems start with between.

An example that should work:
```
?filter[t.finishAt][type]=between&filter[t.date][x]=2021-01-01&filter[t.date][x]=2021-09-01
```
As a special feature, the value t - appeared from the join of the connection of another table, the date field has the datetime format.

```
...
$config->setStrictColumns(false);
$config->setRepositoryCallback([$repository, 'findByOrderBy']);
$queryFilter = new QueryFilter(Response::class);
$response = $queryFilter->getData($config);
...
```
The request hangs on the last line. If you put a dump in front of it - and a breakpoint, everything is ok, and if after - it hangs until the server generates a 504th error (after 5-10 minutes).
Are there any suggestions why this behavior might be? Light filters are ok, even for linking tables, but with between is a problem.

The second part of the question, in this case, should there be filter [t.date] [x] = 2021-01-01 & filter [t.date] [x] = 2021-09-01? Because, in fact, the data is being redefined.

Thank you in advance.

**Comment by denisvmedia** [comment]
You know, I think, there is a mistake in the readme in this case. It should be something like this:

```
?filter[t.date][type]=between&filter[t.date][x]=2021-01-01&filter[t.date][y]=2021-09-01
```

Note filter type type should be applied to `t.date` and also I changed the second `x` to `y`. Would you please try this way and let me know if it works for you?

**Comment by byhaskell** [comment]
@denisvmedia  This is my query prototype, since I have complex filter names, I replaced them with clearer ones for the example, that's why there was an error in the text itself. Thank you and sorry for immediately misleading.

I changed x to y and the result is the same - long execution and 504 server error, unfortunately.

**Comment by denisvmedia** [comment]
I'm afraid that without seeing what is the generated query, it's difficult to say what went wrong. Is it possible that you dump the query (if you need you can clean up the names) and paste it here?

**Comment by byhaskell** [comment]
@denisvmedia Is the request not being formulated in the place where the hangup occurs?

**Comment by denisvmedia** [comment]
I think the request is being generated properly, so the hang is not caused by QueryFilterBundle, but by the DB query. In other words, I think it's most likely a database response that is "guilty" in this case. You can also check "show processlist" in your database (if you use MySQL/MariaDB) if you have a heavy query in your database that lasts long.

**Comment by byhaskell** [comment]
@denisvmedia I forgot to close the question, you were right, the problem was in the request itself. Thanks for the feedback)
