### ISSUE TITLE
setSearchByExtra and getSearchByExtra have incompatible types

### ISSUE THREAD

**Issue by nibynool** [artprima/query-filter-bundle#3]
When using `setSearchByExtra` to provide additional filters it requires I pass a `callable`.  When the `getSearchByExtra` is called, it expects to return an array.

As a side note, it would be great to have some documentation about how the extra values works.

**Comment by nibynool** [comment]
Additional to this the `getAllowedLimits` function does not allow a `null` value to be returned.

**Comment by denisvmedia** [comment]
Thank you for your report, I will take a look at it later. Alternatively, you can provide a pull request for this issue. :)

**Comment by nibynool** [comment]
Wow, that was quick!  Thanks :)

**Comment by rimas-kudelis** [comment]
It seems still unclear how exactly `setSearchByExtra()` is to be used. Neither a `[$field => $value]` array, nor a `[['field' => $field, 'val' => $value']]` array worked for me...

**Comment by rimas-kudelis** [comment]
Ah, I've figured it out, it's:
```php
$filterConfig
    ->setSearchByExtra([
        (new Filter())
            ->setField($field)
            ->setType('eq')
            ->setX($value)
    ]);
```
