### ISSUE TITLE
And and OR filters

### ISSUE THREAD

**Issue by voltagreenben** [artprima/query-filter-bundle#31]
Hello,

Thanks for this great bundle.
I have a question about the **OR** filters
In the document it's described that we can use a connector to achieve an OR filter, like that:
`t.frequency = 10 OR t.frequency >= 85`
=>
`simple=0&filter[0][field]=t.frequency&filter[0][type]=eq&filter[0][x]=10&filter[1][field]=t.frequency&filter[1][type]=gte&filter[1][x]=85&filter[1][connector]=or](http://127.0.0.1:8000/?simple=0&filter%5B0%5D%5Bfield%5D=t.frequency&filter%5B0%5D%5Btype%5D=eq&filter%5B0%5D%5Bx%5D=10&filter%5B1%5D%5Bfield%5D=t.frequency&filter%5B1%5D%5Btype%5D=gte&filter%5B1%5D%5Bx%5D=85&filter%5B1%5D%5Bconnector%5D=or)`

But what if I would like to make this kind of filters:

`(t.frequency = 10 OR t.frequency >= 85) AND t.foo = 'bar'`

I tried to make sub arrays but it didn't work.

Any help would be appreciate.

Thanks

**Comment by denisvmedia** [comment]
Have you tried 

`
simple=0&filter[0][field]=t.frequency&filter[0][type]=eq&filter[0][x]=10&filter[1][field]=t.frequency&filter[1][type]=gte&filter[1][x]=85&filter[1][connector]=or&filter[2][field]=t.foo&filter[2][type]=eq&filter[2][x]=bar&filter[2][connector]=and
`

?

Generally speaking, filters should be applied this way:

> WHERE ((((((((A OR B) AND C) AND D) AND E) OR F) OR G) AND H) AND I)

Thus, what you want should be totally achievable.

**Comment by voltagreenben** [comment]
What I want to do is a bit more complex.
For now, my query looks like this:

```mysql
SELECT t FROM App\Entity\PurchaseEntry t 
INNER JOIN App\Entity\PurchaseEntryReference tr WITH tr.purchase_entry = t.id 
WHERE ((tr.storage_type = ?1 AND t.comment LIKE ?2) OR t.customer_firstname LIKE ?3) OR t.customer_lastname LIKE ?4 
ORDER BY t.id DESC
```

I get that by adding filters like this:

`simple=0&filter[0][field]=tr.storage_type&filter[0][type]=eq&filter[0][x]=nice&filter[1][field]=tr.voltagreen_brand&filter[1][type]=eq&filter[1][x]=ovelo&filter[2][field]=t.comment&filter[2][type]=like&filter[2][x]=64001&filter[3][field]=t.customer_firstname&filter[3][type]=like&filter[3][x]=64001&filter[3][connector]=or&filter[4][field]=t.customer_lastname&filter[4][type]=like&filter[4][x]=64001&filter[4][connector]=or&filter[5][field]=t.prestashop_or_id&filter[5][type]=like&filter[5][x]=64001&filter[5][connector]=or`

But my goal is to have my query like this 
```mysql
SELECT t FROM App\Entity\PurchaseEntry t 
INNER JOIN App\Entity\PurchaseEntryReference tr WITH tr.purchase_entry = t.id 
WHERE ((t.comment LIKE ?1 OR t.customer_firstname LIKE ?2) OR t.customer_lastname LIKE ?3) AND tr.storage_type = ?4 
ORDER BY t.id DESC
```

I can perform this, by doing a tricky stuff: chaging the order of adding filters:
`simple=0&filter[0][field]=t.comment&filter[0][type]=like&filter[0][x]=64001&filter[1][field]=t.customer_firstname&filter[1][type]=like&filter[1][x]=64001&filter[1][connector]=or&filter[2][field]=t.customer_lastname&filter[2][type]=like&filter[2][x]=64001&filter[2][connector]=or&filter[3][field]=t.prestashop_or_id&filter[3][type]=like&filter[3][x]=64001&filter[3][connector]=or&filter[4][field]=tr.storage_type&filter[4][type]=eq&filter[4][x]=nice&filter[5][field]=tr.voltagreen_brand&filter[5][type]=eq&filter[5][x]=ovelo`

But now, I want to add more OR conditions, like this :
```mysql
SELECT t FROM App\Entity\PurchaseEntry t 
INNER JOIN App\Entity\PurchaseEntryReference tr WITH tr.purchase_entry = t.id 
WHERE ((t.comment LIKE ?1 OR t.customer_firstname LIKE ?2) OR t.customer_lastname LIKE ?3) AND tr.storage_type = ?4 OR (t.foo = 'bar' or t.bar = 'foo')
ORDER BY t.id DESC
```

**Comment by denisvmedia** [comment]
The last one is not supported. You will have to revise your conditions, or to compose the condition manually.

P.S. Most likely such complex `where` conditions will lead to poor performance in the DB engine you are using. But that's hard to say without seeing the DB structure and SQL execution plan.

**Comment by voltagreenben** [comment]
Ok, it's a quite specific sql query.
Thanks for your help.
