### ISSUE TITLE
Use Doctrine Paginator instead of PaginationWalker

### ISSUE THREAD

**Issue by rimas-kudelis** [artprima/query-filter-bundle#6]
Doctrine has had a [`Paginator` component](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/pagination.html) ever since 2.2. I think it would make sense to use it instead of relying on your own MySQL-specific `PaginationWalker`. I found that in certain cases, `Paginator` even counts the results more correctly. In particular, `PaginationWalker` counted the results wrongly for me when I was filtering by properties of `OneToMany` relationships.

The code change is rather simple, you just replace the following lines in your repository class:
```php
$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, PaginationWalker::class);
$query->setHint("mysqlWalker.sqlCalcFoundRows", true);
$result = $query->getResult();
$totalRows = $this->_em->getConnection()->query('SELECT FOUND_ROWS()')->fetchColumn();

// return the wrapped result
return new QueryResult($result, $totalRows);
```
with these:
```php
$paginator = new Paginator($query);

return new QueryResult($paginator->getIterator()->getArrayCopy(), count($paginator));
```

I could prepare a PR for that if you're interested. Perhaps it would even make sense to return the `Paginator` itself instead of wrapping its result in `QueryResult` and, subsequently, in `Response` (although that would mean an API change)?

On a separate note, I think it would be great if instead of (or in addition to) getting the `Response` (or `Paginator`) object with only the selected entities and the total count, I could get a `QueryBuilder` with the required filters, offset and limit already appied. This would allow me add extra fine-tuned constraints or perform other actions on the object. Basically, what I want is a library which would parse the query and apply filters to QueryBuilder as opposed to one that does everything from parsing to returning a results object. After seeing how simple to use `Paginator` is, it doesn't seem like instantiating it from outside controller provides any added value. If you agree, I can turn this comment into a separate issue.

**Comment by denisvmedia** [comment]
Hi, I'm aware of Paginator, but in some cases it can be extremely inefficient. But you may use Doctrine Paginator if it works for you. QueryFilterBundle doesn't limit you. Just use Paginator instead of PaginationWalker.

As of your second note, readme actually describes how to get the QueryBuilder:

```
$qb = $this->createQueryBuilder('t')
    ->setFirstResult($args->getOffset())
    ->setMaxResults($args->getLimit());

$proxyQb = new ProxyQueryBuilder($qb, $this->pqbManager);
$qb = $proxyQb->getSortedAndFilteredQueryBuilder($args->getSearchBy(), $args->getSortBy());
```

Does this solve your case? Do you still think there is a need to make changes to the library itself?

**Comment by rimas-kudelis** [comment]
The problem with the code that is in the README is that, just as the README says, I have to put that code in the repository (or service) class, but I am not calling it directly from my controller – instead I'm calling your library, and your library calls that code. The arguments in all these calls are quite strictly defined, so I can't pass any extra data to the function in the repository (or service) which creates that `QueryBuilder` object, then uses it and then discards it.

I see this as a limitation, because the library does not allow grouping conditions – they are all always just appended to the end, resulting in a query like `...WHERE ((((((((A OR B) AND C) AND D) AND E) OR F) OR G) AND H) AND I)` – you get the idea. Luckily I only needed one "OR" connector in my project so far, so I could put that condition first (then again, I had to extend your `BaseConfig` to do that), but If I want to add more complex expressions (e.g. `WHERE (A OR B) AND (C OR D)`, I don't think I have a way to tell the library to do that at the moment.

That's why I thought that allowing me to get a `QueryBuilder` object within the controller would be preferred: getting results from it and counting them is super easy, but (presumably) it would also allow me to add more robust additional criteria on top of the ones from the request. I guess this would also render `setSearchByExtra()` and `getsetSearchByExtra()` methods defined in `ConfigInterface` unnecessary, but on the other hand, it's not like it would hurt keeping them.

**Comment by rimas-kudelis** [comment]
Also, I forgot to mention this in my initial report, but `SELECT FOUND_ROWS()` which you are using, is not just a MySQL-only feature, but it also [has been deprecated since MySQL 8.0.17](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows) and will be removed in a future MySQL version. MySQL themselves suggest to instead do what Doctine's `Paginator` does (except they don't talk about queries with to-many joins). And, as you can see, `Paginator` has an extra argument which can save you from an extra query in cases where to-many joins aren't performed.

I wonder if that extra query is the inefficiency factor that you mentioned. Either way, I'm tempted to remind you that `PaginationWalker` actually returns wrong number of found rows when to-many joins are involved. :) I wonder how you'd solve it without doing what `Paginator` does.

**Comment by denisvmedia** [comment]
> Also, I forgot to mention this in my initial report, but `SELECT FOUND_ROWS()` which you are using

Could you please point the file in the repository that uses it? (except readme)

**Comment by denisvmedia** [comment]
> I wonder if that extra query is the inefficiency factor that you mentioned. Either way, I'm tempted to remind you that PaginationWalker actually returns wrong number of found rows when to-many joins are involved. :) I wonder how you'd solve it without doing what Paginator does.

Ok, if you insist, you may provide a PR to readme :) Other than that no changes to the core library are required in your case ;)

**Comment by rimas-kudelis** [comment]
>> Also, I forgot to mention this in my initial report, but `SELECT FOUND_ROWS()` which you are using
>
>Could you please point the file in the repository that uses it? (except readme)

The PaginationWalker uses the other half of that feature (`SELECT SQL_CALC_FOUND_ROWS`).

**Comment by denisvmedia** [comment]
> The PaginationWalker uses the other half of that feature (`SELECT SQL_CALC_FOUND_ROWS`).

Yes, but you are not forced to use it :) Anyway, feel free to provide a PR, but please try to not break backwards compatibility and make sure you cover the new parts with tests.

**Comment by denisvmedia** [comment]
In addition: 

> then again, I had to extend your BaseConfig to do that

Actually BaseConfig is meant to be extended (even its name is a hint to it).
