### ISSUE TITLE
If searchByExtra contains an `OR` condition, the query becomes totally wrong

### ISSUE THREAD

**Issue by rimas-kudelis** [artprima/query-filter-bundle#8]
This library currently does not allow grouping conditions – they are all always just appended to the end, resulting in a query like `...WHERE ((((((((A OR B) AND C) AND D) AND E) OR F) OR G) AND H) AND I)` – you get the idea, and I wrote about it before in #6.

What I was wrong about there is that this problem does not affect me, because I only planned to use one OR condition in my `searchByExtra` arguments, and I assumed that these were prepended to the query.

Apparently this is not the case. `searchByExtra` are currently appended to the end of the query, so each `OR` condition will cause the filter to yield completely unexpected results.

Simple example:
Let's say you have a bookstore and the user searches for books by title and in the backend you add extra filters to only return books which are currently available or are scheduled to arrive soon.
The user asks sends `filter[title]=Potter`.
Your query becomes something like this:
`... WHERE (((title LIKE "%Potter%") AND status="available") OR date_of_arrival <= "+5 days from now")`

Instead of returning what the user expects, this will return all books which have "Potter" in title and are available and all the books scheduled to arrive soon.

**Comment by denisvmedia** [comment]
Thank you for your PR. I'd eagerly accept it. But do you have any ideas how we could make it even better? (considering, that breaking API is ok at this moment - later we might find a compromise or just issue a new major version)

**Comment by rimas-kudelis** [comment]
I do, but if breaking the API is ok, I'd want to break it even more! :)

Regarding this particular issue: changing the signature of `QueryFilterArgs` to return `searchBy` and `searchByExtra` separately and updating `ProxyQueryBuilder::getSortedAndFilteredQueryBuilder()` accordingly would probably do the job (actually, the latter should just accept an instance of `QueryFilterArgs` instead of expecting the repository to expand it into two separate arguments).

But like I said, there's more. Looking at the README, all the code that is currently suggested to go to `ItemRepository` looks like boilerplate code to me, so perhaps it could be moved into the this `QueryFilter` instead. `ConfigInterface` could then accept a repository instead of (or in addition to) a callback, and maybe a string to be used as an alias argument when calling `createQueryBuilder()` of that repository.

I've written a trait which automatically adds immediate `leftJoin` calls when building the query from `QueryFilterArgs` (by "immediate" I mean only the first-level relationships with the main entity). It would probably render having extra code in the repository absolutely unnecessary if improved to cater for deeper relationships as well.

**Comment by rimas-kudelis** [comment]
Can you accept the PR for now? We don't have to close this issue, but that would really help me in the short term. :)

**Comment by denisvmedia** [comment]
Accepted, merged, released. :)

**Comment by rimas-kudelis** [comment]
Let's reopen this though.

**Comment by rimas-kudelis** [comment]
@denisvmedia I can't see the change in 1.3.0 though. You probably tagged a wrong commit.
